blueprint:
  name: Update Aqara TRV E1 temperature using external sensor
  description: |
    Updates the Aqara TRV E1 temperature using an external temperature sensor.  
    This blueprint can only be used whith Aqara TRV E1 provided by Zigbee2MQTT!
  domain: automation
  author: Janek Kröger (@jkrgr)
  input:
    temperature_sensor:
      name: External temperature sensor
      description: The external temperature sensor to use.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    trv:
      name: TRV
      description: TRV on which the external temperate sensor should be bind to.
      selector:
        entity:
          integration: mqtt
          domain: climate
    trv_sensor:
      name: TRV sensor
      description: Sensor entity of the TRV which describes if internal or external temperature should be used.
      selector:
        entity:
          domain: select

mode: restart

trigger:
  - platform: state
    entity_id: !input temperature_sensor

variables:
  temperature_sensor: !input temperature_sensor
  trv: !input trv
  trv_friendly_name: "{{ state_attr(trv, 'friendly_name') }}"
  trv_device_id: "{{ device_id(trv) }}"

action:
  - device_id: "{{ trv_device_id }}"
    domain: select
    entity_id: !input trv_sensor
    type: select_option
    option: external

  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0

  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: zigbee2mqtt/{{ trv_friendly_name }}/set/sensor_temp
      payload_template: |-
        {{
          ( states(temperature_sensor) | float(0) | round(1) )
        }}
